import {
  BadgeDollarSign,
  Building2,
  Calendar,
  ClipboardList,
  FileSpreadsheet,
  GitBranch,
  Heart,
  Landmark,
  Ticket,
  Users,
  Wallet,
} from "lucide-react";
import { BOARD_MEMBERSHIP_ROLES } from "../../utils/memberBenefits";
import {
  buildAssemblyMembersRows,
  buildAssemblyMembersSummary,
  buildAidsRows,
  buildBankChargesRows,
  buildBoardAllowancesRows,
  buildBoardMeetingsRows,
  buildBoardMembersRows,
  buildBookingsRows,
  buildCarryForwardAuditRows,
  buildEmployeesRows,
  buildEventsRows,
  buildIssuedChecksRows,
  buildMemberBenefitsRows,
  buildMemberMovementsReportRows,
  buildMemberMovementsSummary,
  buildMonthlyFinancialAnalysisRows,
  buildMonthlyFinancialAnalysisSummary,
  buildSettlementRows,
  buildSimplifiedBalanceSheetRows,
  buildSimplifiedBalanceSheetSummary,
  buildTreasuryRows,
} from "./reportDataBuilders";
import { compareArabic, getBoardExecutiveSortBucket, getTodayISO, sortByDateCheckEmployee, sortByDateRefName } from "./reportUtils";
import { formatMoney } from "../../utils/numberFormat";
import { compareJobNumberValues, getBoardRoleRank } from "../board/boardMembershipRules";

const REPORTS_NOW = new Date();
const CURRENT_REPORT_YEAR = String(REPORTS_NOW.getFullYear());
const CURRENT_REPORT_MONTH = `${String(REPORTS_NOW.getMonth() + 1).padStart(2, "0")} - ${[
  "يناير",
  "فبراير",
  "مارس",
  "أبريل",
  "مايو",
  "يونيو",
  "يوليو",
  "أغسطس",
  "سبتمبر",
  "أكتوبر",
  "نوفمبر",
  "ديسمبر",
][REPORTS_NOW.getMonth()]}`;

export const REPORT_MODULES = {
  treasury_ledger: {
    id: "treasury_ledger",
    title: "كشف الحركة المالية الشامل",
    subtitle: "سجل موحّد للحركات الواردة والمنصرفة من المصادر القديمة والجديدة",
    icon: Wallet,
    sources: ["transactions", "issued_checks"],
    dateField: "date",
    orientation: "portrait",
    sortLabel: "التاريخ تصاعديًا ثم رقم الشيك/المرجع ثم رقم العامل",
    searchPlaceholder: "ابحث بالتاريخ أو الجهة أو البيان أو المرجع...",
    emptyMessage: "لا توجد حركات مالية مطابقة للفلاتر الحالية.",
    fields: [
      { key: "date", label: "التاريخ" },
      { key: "typeLabel", label: "النوع" },
      { key: "reference", label: "المرجع" },
      { key: "party", label: "الجهة / المستفيد" },
      { key: "statement", label: "البيان" },
      { key: "income", label: "وارد", currency: true },
      { key: "expense", label: "منصرف", currency: true },
      { key: "statusLabel", label: "الحالة" },
    ],
    buildRows: buildTreasuryRows,
    sortRows: (rows) => sortByDateCheckEmployee(rows, "date", "reference", "memberId", "party"),
  },
  issued_checks: {
    id: "issued_checks",
    title: "الشيكات الصادرة",
    subtitle: "يشمل الإعانات والسلف والرحلات والفاعليات وباقي الشيكات الإدارية",
    icon: FileSpreadsheet,
    sources: ["transactions", "issued_checks"],
    dateField: "date",
    orientation: "portrait",
    sortLabel: "التاريخ تصاعديًا ثم رقم الشيك ثم رقم العامل",
    searchPlaceholder: "ابحث بالمستفيد أو رقم الشيك أو بند الصرف...",
    emptyMessage: "لا توجد شيكات صادرة مطابقة.",
    fields: [
      { key: "date", label: "التاريخ" },
      { key: "typeLabel", label: "نوع الشيك" },
      { key: "reference", label: "رقم الشيك" },
      { key: "party", label: "المستفيد" },
      { key: "purpose", label: "الغرض" },
      { key: "amount", label: "القيمة", currency: true },
      { key: "settlementLabel", label: "التسوية" },
      { key: "settlementStatusLabel", label: "الموقف" },
    ],
    buildRows: buildIssuedChecksRows,
    sortRows: (rows) => sortByDateCheckEmployee(rows, "date", "reference", "memberId", "party"),
  },
  settlements: {
    id: "settlements",
    title: "أرشيف التسويات المعتمدة",
    subtitle: "يعرض الشيكات والسلف التي أغلقت بتسوية فعلية وفواتير معتمدة",
    icon: ClipboardList,
    sources: ["transactions", "issued_checks"],
    dateField: "approvalDate",
    orientation: "portrait",
    sortLabel: "التاريخ تصاعديًا ثم رقم الشيك ثم رقم العامل",
    searchPlaceholder: "ابحث بالمسؤول أو رقم الشيك أو نوع التسوية...",
    emptyMessage: "لا توجد تسويات معتمدة مطابقة.",
    fields: [
      { key: "approvalDate", label: "تاريخ الاعتماد" },
      { key: "checkDate", label: "تاريخ الشيك" },
      { key: "typeLabel", label: "النوع" },
      { key: "reference", label: "رقم الشيك" },
      { key: "party", label: "المسؤول" },
      { key: "checkAmount", label: "القيمة", currency: true },
      { key: "spent", label: "المنصرف", currency: true },
      { key: "returned", label: "الرصيد", currency: true },
      { key: "invoicesCount", label: "الفواتير" },
      { key: "returnStatus", label: "الموقف" },
    ],
    buildRows: buildSettlementRows,
    sortRows: (rows) => sortByDateCheckEmployee(rows, "approvalDate", "reference", "memberId", "party"),
  },
  carry_forward_audit: {
    id: "carry_forward_audit",
    title: "تدقيق الأرصدة المرحلة",
    subtitle: "سلسلة كل مسؤول: سلفة ثم رصيد مرحل ثم السلفة التالية",
    icon: GitBranch,
    sources: ["transactions", "issued_checks"],
    dateField: "checkDate",
    orientation: "portrait",
    sortLabel: "التاريخ تصاعديًا ثم رقم الشيك ثم رقم العامل",
    searchPlaceholder: "ابحث باسم المسؤول أو رقم الشيك...",
    emptyMessage: "لا توجد أرصدة مرحلة أو تسويات معتمدة مطابقة.",
    fields: [
      { key: "party", label: "المسؤول" },
      { key: "checkDate", label: "تاريخ الشيك" },
      { key: "reference", label: "رقم الشيك" },
      { key: "advanceAmount", label: "أصل السلفة", currency: true },
      { key: "carriedIn", label: "الرصيد المرحل المستخدم", currency: true },
      { key: "spent", label: "المصروف", currency: true },
      { key: "remaining", label: "المتبقي المرحل", currency: true },
      { key: "returnMode", label: "طريقة معالجة المتبقي" },
      { key: "nextAdvance", label: "السلفة التالية" },
    ],
    buildRows: buildCarryForwardAuditRows,
    sortRows: (rows) => sortByDateCheckEmployee(rows, "checkDate", "reference", "memberId", "party"),
  },
  bank_charges: {
    id: "bank_charges",
    title: "الخصومات والعمولات المباشرة",
    subtitle: "المصاريف البنكية التي تخصم من كشف الحساب دون إصدار شيك",
    icon: BadgeDollarSign,
    sources: ["transactions"],
    dateField: "date",
    orientation: "portrait",
    sortLabel: "التاريخ تصاعديًا ثم رقم الشيك/المرجع ثم رقم العامل",
    searchPlaceholder: "ابحث بالتصنيف البنكي أو المرجع أو البيان...",
    emptyMessage: "لا توجد خصومات مباشرة مطابقة.",
    fields: [
      { key: "date", label: "التاريخ" },
      { key: "category", label: "التصنيف" },
      { key: "reference", label: "المرجع البنكي" },
      { key: "statement", label: "البيان" },
      { key: "amount", label: "القيمة", currency: true },
      { key: "statusLabel", label: "الحالة" },
    ],
    buildRows: buildBankChargesRows,
    sortRows: (rows) => sortByDateCheckEmployee(rows, "date", "reference", "memberId", "category"),
  },
  aids: {
    id: "aids",
    title: "تقرير الإعانات",
    subtitle: "سجل الرعايات المصروفة للأعضاء مع نوع الرعاية والواقعة المرتبطة بها",
    icon: Heart,
    sources: ["transactions", "issued_checks"],
    dateField: "date",
    orientation: "portrait",
    sortLabel: "التاريخ تصاعديًا ثم رقم الشيك ثم رقم العامل",
    searchPlaceholder: "ابحث باسم العضو أو نوع الرعاية أو رقم الشيك...",
    // ...
    customConfig: (currentRows) => {
      const aidRows = currentRows.filter((r) => (r.category || r.typeLabel) === "رعاية");
      return {
        indexFields: ["name", "category", "amount"],
        cards: [
          { label: "إجمالي عدد الرعايات", value: String(aidRows.length), color: "rose" },
          { label: "إجمالي مبالغ الرعايات", value: formatMoney(aidRows.reduce((s, r) => s + Number(r.amount || 0), 0)), color: "rose" },
        ],
      };
    },
    sections: [],
    fields: [
      { key: "name", label: "اسم العضو" },
      { key: "party", label: "المستفيد" },
      { key: "amount", label: "المبلغ", currency: true },
      { key: "category", label: "نوع الرعاية" },
      { key: "aidRel", label: "صلة القرابة" },
      { key: "date", label: "التاريخ" },
      { key: "checkNum", label: "رقم الشيك" },
      { key: "notes", label: "البيان" },
    ],
    buildRows: buildAidsRows,
    sortRows: (rows) => sortByDateCheckEmployee(rows, "date", "reference", "memberId", "memberName"),
  },
  general_assembly_members: {
    id: "general_assembly_members",
    title: "كشف بأسماء الجمعية العمومية (الأعضاء)",
    subtitle: "سجل الأعضاء العاديين مع بيانات الإدارة والمؤهل وتاريخ الانضمام والحالة الحالية",
    icon: Users,
    sources: ["employees", "board_memberships", "board_terms"],
    dateField: "unionJoinDate",
    orientation: "portrait",
    sortLabel: "رقم العامل تصاعديًا ثم الاسم",
    searchPlaceholder: "ابحث بالاسم أو الكود أو الإدارة أو المؤهل أو الوظيفة...",
    emptyMessage: "لا توجد بيانات أعضاء جمعية عمومية مطابقة للفلاتر الحالية.",
    customFilters: [
      { key: "administration", label: "حسب الإدارة", type: "select", rowKey: "administration" },
      { key: "memberStateNormalized", label: "حسب حالة العضوية", type: "select", rowKey: "memberStateNormalized" },
      { key: "qualification", label: "حسب المؤهل", type: "select", rowKey: "qualification" },
      { key: "jobId", label: "حسب كود الموظف", type: "text", rowKey: "jobId", placeholder: "اكتب الكود الوظيفي" },
    ],
    fields: [
      { key: "jobId", label: "الكود" },
      { key: "name", label: "الاسم" },
      { key: "jobTitle", label: "الوظيفة" },
      { key: "administration", label: "الإدارة" },
      { key: "qualification", label: "المؤهل" },
      { key: "unionJoinDate", label: "تاريخ الانضمام" },
      { key: "memberStateNormalized", label: "الحالة" },
      { key: "ageLabel", label: "العمر" },
      { key: "phone", label: "الهاتف" },
    ],
    buildRows: buildAssemblyMembersRows,
    buildSummary: buildAssemblyMembersSummary,
    sortRows: (rows) => [...rows].sort(
      (a, b) =>
        compareArabic(a.jobId, b.jobId) ||
        compareArabic(a.name, b.name)
    ),
  },
  employees: {
    id: "employees",
    title: "سجل الأعضاء",
    subtitle: "بيانات العضوية والخدمة والحالة النقابية في صورة تقرير إداري موحد",
    icon: Users,
    sources: ["employees"],
    dateField: "",
    orientation: "portrait",
    sortLabel: "الكود الوظيفي تصاعديًا ثم الاسم",
    searchPlaceholder: "ابحث بالكود أو الاسم أو الصفة أو جهة العمل...",
    emptyMessage: "لا توجد بيانات أعضاء مطابقة.",
    customFilters: [
      { key: "membershipStatus", label: "صفة العضوية", type: "select", rowKey: "membershipStatus", cascade: true },
      { key: "memberState", label: "الحالة", type: "select", rowKey: "memberState", cascade: true },
      { key: "gender", label: "النوع", type: "select", rowKey: "gender", cascade: true },
    ],
    fields: [
      { key: "jobId", label: "الكود" },
      { key: "name", label: "الاسم" },
      { key: "membershipStatus", label: "الصفة" },
      { key: "memberState", label: "الحالة" },
      { key: "jobTitle", label: "المسمى الوظيفي" },
      { key: "workplace", label: "جهة العمل" },
      { key: "phone", label: "الموبايل" },
      { key: "subscriptionStatus", label: "الاشتراك" },
      { key: "retirementDate", label: "تاريخ المعاش" },
    ],
    buildRows: buildEmployeesRows,
    sortRows: (rows) => [...rows].sort((a, b) => compareArabic(a.jobId, b.jobId) || compareArabic(a.name, b.name)),
  },
  board_members: {
    id: "board_members",
    title: "تشكيل مجلس الإدارة",
    subtitle: "أعضاء المجلس الحاليين مرتبين إداريًا حسب الصفة ثم الاسم",
    icon: Building2,
    sources: ["employees", "board_memberships", "board_terms"],
    dateField: "",
    orientation: "portrait",
    sortLabel: "الأعضاء التنفيذيون أولًا ثم أعضاء مجلس الإدارة ثم رقم العامل",
    searchPlaceholder: "ابحث بالصفة أو الاسم أو جهة العمل...",
    emptyMessage: "لا توجد بيانات لأعضاء المجلس.",
    fields: [
      { key: "role", label: "الصفة" },
      { key: "name", label: "الاسم" },
      { key: "jobId", label: "الكود" },
      { key: "nationalId", label: "الرقم القومي" },
      { key: "gender", label: "النوع" },
      { key: "phone", label: "الموبايل" },
      { key: "workplace", label: "جهة العمل" },
      { key: "memberState", label: "الحالة" },
      { key: "joinDate", label: "تاريخ الالتحاق" },
      { key: "endDate", label: "تاريخ الانتهاء" },
    ],
    buildRows: buildBoardMembersRows,
    sortRows: (rows) =>
      [...rows].sort(
        (a, b) =>
          getBoardExecutiveSortBucket(a.role) - getBoardExecutiveSortBucket(b.role) ||
          getBoardRoleRank(a.role) - getBoardRoleRank(b.role) ||
          compareJobNumberValues(a.jobId, b.jobId)
      ),
  },
  board_meetings: {
    id: "board_meetings",
    title: "سجل اجتماعات المجلس",
    subtitle: "محاضر الاجتماعات بعدد الحضور والقرارات والأعضاء المشاركين",
    icon: Landmark,
    sources: ["board_meetings", "employees", "board_memberships", "board_terms"],
    dateField: "date",
    orientation: "portrait",
    sortLabel: "التاريخ تصاعديًا ثم عنوان الاجتماع",
    searchPlaceholder: "ابحث بعنوان الاجتماع أو أسماء الحضور...",
    emptyMessage: "لا توجد اجتماعات مجلس مطابقة.",
    fields: [
      { key: "date", label: "التاريخ" },
      { key: "title", label: "عنوان الاجتماع" },
      { key: "statusLabel", label: "الحالة" },
      { key: "attendeesCount", label: "الحضور" },
      { key: "absenteesCount", label: "الغياب" },
      { key: "decisionsCount", label: "القرارات" },
      { key: "approvedDecisions", label: "القرارات المعتمدة" },
      { key: "absenteesNames", label: "المتغيبون" },
    ],
    buildRows: buildBoardMeetingsRows,
    sortRows: (rows) => sortByDateRefName(rows, "date", "title", "title"),
  },
  board_allowances: {
    id: "board_allowances",
    title: "بدلات مجلس الإدارة",
    subtitle: "مستخرج مجمع من التسويات المعتمدة لبدلات الجلسات والانتقال والضيافة",
    icon: BadgeDollarSign,
    sources: ["employees", "transactions", "issued_checks", "board_memberships", "board_terms"],
    dateField: "lastAllowanceDate",
    orientation: "portrait",
    sortLabel: "الأعضاء التنفيذيون أولًا ثم أعضاء مجلس الإدارة ثم رقم العامل",
    searchPlaceholder: "ابحث بالاسم أو الصفة أو تاريخ آخر بدل...",
    emptyMessage: "لا توجد بدلات مجلس معتمدة مطابقة.",
    fields: [
      { key: "role", label: "الصفة" },
      { key: "name", label: "الاسم" },
      { key: "jobId", label: "الكود" },
      { key: "lastAllowanceDate", label: "آخر اعتماد" },
      { key: "sessionsAllowance", label: "بدل جلسات", currency: true },
      { key: "travelAllowance", label: "بدل انتقال", currency: true },
      { key: "hospitalityAllowance", label: "بدل ضيافة", currency: true },
      { key: "totalAllowance", label: "الإجمالي", currency: true },
    ],
    buildRows: (sourceData) => buildBoardAllowancesRows(sourceData, BOARD_MEMBERSHIP_ROLES),
    sortRows: (rows) =>
      [...rows].sort(
        (a, b) =>
          getBoardExecutiveSortBucket(a.role) - getBoardExecutiveSortBucket(b.role) ||
          (a.roleWeight ?? BOARD_MEMBERSHIP_ROLES.length) - (b.roleWeight ?? BOARD_MEMBERSHIP_ROLES.length) ||
          compareJobNumberValues(a.jobId, b.jobId)
      ),
  },
  balance_sheet_simplified: {
    id: "balance_sheet_simplified",
    title: "Balance Sheet مبسط",
    subtitle: "ملخص مالي مبسط يوضح الرصيد النقدي والسلف الجارية والتسويات والأرصدة المدينة والدائنة",
    icon: Landmark,
    sources: ["transactions", "issued_checks"],
    dateField: "",
    orientation: "portrait",
    showTotals: false,
    sortLabel: "حسب التصنيف المحاسبي",
    searchPlaceholder: "ابحث باسم البند أو التصنيف أو الوصف...",
    emptyMessage: "لا توجد بيانات مالية كافية لعرض الميزان المبسط.",
    fields: [
      { key: "category", label: "التصنيف" },
      { key: "item", label: "البند" },
      { key: "amount", label: "القيمة", currency: true },
      { key: "countLabel", label: "العدد / الحالة" },
      { key: "note", label: "الشرح المحاسبي" },
    ],
    buildRows: buildSimplifiedBalanceSheetRows,
    buildSummary: buildSimplifiedBalanceSheetSummary,
    sortRows: (rows) => rows,
  },
  monthly_financial_analysis: {
    id: "monthly_financial_analysis",
    title: "تقرير التحليل المالي الشهري",
    subtitle: "رؤية تحليلية للإيرادات والمصروفات وصافي الشهر والنمو والتوزيعات وأعلى الجهات والمصادر",
    icon: Wallet,
    sources: ["transactions", "issued_checks"],
    dateField: "date",
    orientation: "landscape",
    sortLabel: "التاريخ تصاعديًا ثم رقم الشيك/المرجع ثم رقم العامل",
    searchPlaceholder: "ابحث في الجهة أو المصدر أو بند الصرف أو البيان...",
    emptyMessage: "لا توجد بيانات مالية مطابقة للشهر أو الفلاتر المحددة.",
    customFilters: [
      { key: "monthLabel", label: "الشهر", type: "select", rowKey: "monthLabel", defaultValue: CURRENT_REPORT_MONTH },
      { key: "yearLabel", label: "السنة", type: "select", rowKey: "yearLabel", defaultValue: CURRENT_REPORT_YEAR },
    ],
    fields: [
      { key: "date", label: "التاريخ" },
      { key: "typeLabel", label: "النوع" },
      { key: "party", label: "الجهة" },
      { key: "incomeSourceLabel", label: "مصدر الإيراد" },
      { key: "expenseBucket", label: "بند المصروف" },
      { key: "income", label: "إيراد", currency: true },
      { key: "expense", label: "مصروف", currency: true },
      { key: "analysisBucket", label: "التصنيف" },
    ],
    buildRows: buildMonthlyFinancialAnalysisRows,
    buildSummary: buildMonthlyFinancialAnalysisSummary,
    sortRows: (rows) => sortByDateCheckEmployee(rows, "date", "reference", "memberId", "party"),
  },
  events: {
    id: "events",
    title: "سجل الفعاليات والأنشطة",
    subtitle: "جدول الفعاليات بالسعة والحجز والتسعير والدعم المعتمد",
    icon: Calendar,
    sources: ["events"],
    dateField: "date",
    orientation: "portrait",
    sortLabel: "التاريخ تصاعديًا ثم رقم الشيك/المرجع ثم رقم العامل",
    searchPlaceholder: "ابحث باسم الفعالية أو النوع أو المكان...",
    emptyMessage: "لا توجد فعاليات مطابقة.",
    fields: [
      { key: "date", label: "التاريخ" },
      { key: "title", label: "اسم الفعالية" },
      { key: "type", label: "النوع" },
      { key: "location", label: "المكان" },
      { key: "capacity", label: "السعة" },
      { key: "booked", label: "المحجوز" },
      { key: "available", label: "المتاح" },
      { key: "bookingWindow", label: "فترة الحجز" },
      { key: "pricing", label: "التسعير" },
      { key: "statusLabel", label: "الحالة" },
    ],
    buildRows: (sourceData) => buildEventsRows(sourceData, getTodayISO()),
    sortRows: (rows) => sortByDateCheckEmployee(rows, "date", "reference", "memberId", "title"),
  },
  bookings: {
    id: "bookings",
    title: "حجوزات الفعاليات",
    subtitle: "سجل الحجز والدفع والتكلفة والحالة لكل مشترك",
    icon: Ticket,
    sources: ["event_bookings", "events"],
    dateField: "eventDate",
    orientation: "portrait",
    sortLabel: "التاريخ تصاعديًا ثم رقم الشيك/المرجع ثم رقم العامل",
    searchPlaceholder: "ابحث بالفعالية أو اسم العضو أو الكود أو حالة الحجز...",
    emptyMessage: "لا توجد حجوزات مطابقة.",
    fields: [
      { key: "eventDate", label: "تاريخ الفعالية" },
      { key: "eventTitle", label: "الفعالية" },
      { key: "memberName", label: "العضو" },
      { key: "memberId", label: "الكود" },
      { key: "totalPax", label: "الأفراد" },
      { key: "totalCost", label: "التكلفة", currency: true },
      { key: "statusLabel", label: "الحالة" },
      { key: "paymentSummary", label: "الدفع" },
    ],
    buildRows: buildBookingsRows,
    sortRows: (rows) => sortByDateCheckEmployee(rows, "eventDate", "reference", "memberId", "memberName"),
  },
  member_movements: {
    id: "member_movements",
    title: "تقرير حركة الأعضاء خلال فترة",
    subtitle: "كشف زمني للحركات الإدارية والنهائية للأعضاء مع متابعة نوع الحركة وحالة الاعتماد والحالة قبل وبعد الحركة",
    icon: GitBranch,
    sources: ["member_movements"],
    dateField: "effectiveDateRaw",
    orientation: "portrait",
    sortLabel: "التاريخ تصاعديًا ثم رقم الشيك/المرجع ثم رقم العامل",
    searchPlaceholder: "ابحث باسم العضو أو الكود أو نوع الحركة أو السبب أو الملاحظات...",
    emptyMessage: "لا توجد حركات أعضاء مطابقة للفترة أو الفلاتر الحالية.",
    customFilters: [
      { key: "movementLabel", label: "حسب نوع الحركة", type: "select", rowKey: "movementLabel", cascade: true },
      { key: "statusLabel", label: "حسب حالة الاعتماد", type: "select", rowKey: "statusLabel", cascade: true },
      { key: "movementCategory", label: "حسب فئة الحركة", type: "select", rowKey: "movementCategory" },
      { key: "toState", label: "حسب الحالة بعد الحركة", type: "select", rowKey: "toState" },
    ],
    fields: [
      { key: "effectiveDateLabel", label: "التاريخ الفعلي" },
      { key: "decisionDateLabel", label: "تاريخ القرار" },
      { key: "memberName", label: "اسم العضو" },
      { key: "memberCode", label: "الكود" },
      { key: "movementLabel", label: "نوع الحركة" },
      { key: "movementCategory", label: "الفئة" },
      { key: "statusLabel", label: "الاعتماد" },
      { key: "fromState", label: "قبل الحركة" },
      { key: "toState", label: "بعد الحركة" },
      { key: "workplace", label: "جهة العمل" },
      { key: "jobTitle", label: "الوظيفة" },
      { key: "reason", label: "السبب" },
      { key: "notes", label: "الملاحظات" },
    ],
    buildRows: buildMemberMovementsReportRows,
    buildSummary: buildMemberMovementsSummary,
    sortRows: (rows) => sortByDateCheckEmployee(rows, "effectiveDateRaw", "reference", "memberCode", "memberName"),
  },
  member_benefits: {
    id: "member_benefits",
    title: "مزايا ودعم الأعضاء",
    subtitle: "كل ما تم تسجيله لصالح الأعضاء من دعم فعاليات ومزايا وجوائز وخدمات",
    icon: Heart,
    sources: ["member_benefits"],
    dateField: "date",
    orientation: "portrait",
    sortLabel: "التاريخ تصاعديًا ثم رقم الشيك/المرجع ثم رقم العامل",
    searchPlaceholder: "ابحث باسم العضو أو نوع المزية أو المرجع...",
    emptyMessage: "لا توجد مزايا أعضاء مطابقة.",
    fields: [
      { key: "date", label: "التاريخ" },
      { key: "memberName", label: "العضو" },
      { key: "memberId", label: "الكود" },
      { key: "benefitType", label: "نوع المزية" },
      { key: "eventTitle", label: "المرجع" },
      { key: "sourceLabel", label: "المصدر" },
      { key: "statusLabel", label: "الحالة" },
      { key: "amount", label: "القيمة", currency: true },
      { key: "notes", label: "الملاحظات" },
    ],
    buildRows: buildMemberBenefitsRows,
    sortRows: (rows) => sortByDateCheckEmployee(rows, "date", "reference", "memberId", "memberName"),
  },
};

export const REPORT_GROUPS = [
  {
    id: "finance",
    label: "الماليات",
    moduleIds: ["treasury_ledger", "issued_checks", "settlements", "bank_charges", "aids", "balance_sheet_simplified", "monthly_financial_analysis"],
  },
  {
    id: "members",
    label: "شؤون الأعضاء",
    moduleIds: ["general_assembly_members", "employees", "member_movements", "member_benefits"],
  },
  {
    id: "board",
    label: "مجلس الإدارة",
    moduleIds: ["board_members", "board_meetings", "board_allowances"],
  },
  {
    id: "activities",
    label: "الأنشطة والفاعليات",
    moduleIds: ["events", "bookings"],
  },
];
