export const UNION_ACTIVITY_TYPES = [
  {
    id: "trips",
    title: "الرحلات",
    subtitle: "رحلات ترفيهية ودينية وثقافية",
    icon: "🚌",
    eventType: "رحلة ترفيهية",
    benefitType: "دعم رحلة",
    extraFields: [
      { key: "destination", label: "جهة السفر", listKey: "union_trip_destinations", type: "dropdown" },
      { key: "tripKind", label: "نوع الرحلة", listKey: "union_trip_kinds", type: "dropdown", defaultOptions: ["ترفيهية", "دينية", "ثقافية", "عمرة"] },
      { key: "departDate", label: "تاريخ الذهاب", type: "date" },
      { key: "returnDate", label: "تاريخ العودة", type: "date" },
      { key: "transport", label: "وسيلة النقل", listKey: "union_transport", type: "dropdown", defaultOptions: ["أتوبيس", "قطار", "طيران", "عبّارة"] },
      { key: "hotel", label: "الفندق / الإقامة", type: "text" },
    ],
  },
  {
    id: "resorts",
    title: "المصايف",
    subtitle: "رحلات المصيف المتكررة",
    icon: "🏖",
    eventType: "رحلة ترفيهية",
    benefitType: "دعم رحلة",
    extraFields: [
      { key: "destination", label: "المصيف", listKey: "union_resort_destinations", type: "dropdown", defaultOptions: ["مرسى مطروح", "الإسكندرية", "الغردقة", "شرم الشيخ", "رأس البر"] },
      { key: "season", label: "الفوج / الموسم", listKey: "union_resort_seasons", type: "dropdown", defaultOptions: ["الفوج الأول", "الفوج الثاني", "الفوج الثالث"] },
      { key: "departDate", label: "تاريخ الذهاب", type: "date" },
      { key: "returnDate", label: "تاريخ العودة", type: "date" },
      { key: "accommodation", label: "نوع الإقامة", listKey: "union_accommodation", type: "dropdown", defaultOptions: ["شقة", "شاليه", "غرفة فندقية"] },
    ],
  },
  {
    id: "books",
    title: "الكتب المدعمة",
    subtitle: "مخزون الكتب بأسعار مدعمة",
    icon: "📚",
    eventType: "كتب مدعمة",
    benefitType: "خصم كتب",
    stockMode: true,
    extraFields: [
      { key: "publisher", label: "الناشر", listKey: "union_publishers", type: "dropdown" },
      { key: "bookCategory", label: "التصنيف", listKey: "union_book_categories", type: "dropdown", defaultOptions: ["ديني", "ثقافي", "تعليمي", "أطفال"] },
      { key: "coverPrice", label: "سعر الغلاف", type: "number" },
      { key: "stockQty", label: "الكمية بالمخزون", type: "number" },
      { key: "maxPerMember", label: "الحد الأقصى للعضو", type: "number" },
    ],
  },
  {
    id: "electronics",
    title: "الأجهزة والإلكترونيات",
    subtitle: "عروض الأجهزة بالتقسيط بدون فوائد",
    icon: "📱",
    eventType: "عرض أجهزة وموبايل",
    benefitType: "دعم فعالية",
    installmentMode: true,
    extraFields: [
      { key: "deviceCategory", label: "الفئة", listKey: "union_device_categories", type: "dropdown", defaultOptions: ["موبايل", "لابتوب", "شاشة", "أجهزة منزلية"] },
      { key: "deviceBrand", label: "الماركة", listKey: "union_device_brands", type: "dropdown" },
      { key: "deviceModel", label: "الموديل", type: "text" },
      { key: "installmentMonths", label: "عدد الشهور", listKey: "union_installment_months", type: "dropdown", defaultOptions: ["6", "10", "12", "18", "24"] },
    ],
  },
  {
    id: "exhibitions",
    title: "المعارض",
    subtitle: "معارض السلع والأجهزة والكتب",
    icon: "🏪",
    eventType: "معرض",
    benefitType: "دعم فعالية",
    extraFields: [
      { key: "exhibitionType", label: "نوع المعرض", listKey: "union_exhibition_types", type: "dropdown", defaultOptions: ["أجهزة", "سلع معمرة", "كتب", "ملابس"] },
      { key: "venue", label: "مكان المعرض", type: "text" },
      { key: "organizer", label: "الجهة المنظمة / العارض", type: "text" },
      { key: "startDate", label: "تاريخ البدء", type: "date" },
      { key: "endDate", label: "تاريخ الانتهاء", type: "date" },
    ],
  },
  {
    id: "iftar",
    title: "الإفطار الجماعي",
    subtitle: "موائد الإفطار الجماعي",
    icon: "🌙",
    eventType: "حفل إفطار",
    benefitType: "دعم وجبات",
    extraFields: [
      { key: "venue", label: "مكان الإفطار", type: "text" },
      { key: "mealType", label: "نوع الوجبة", listKey: "union_meal_types", type: "dropdown", defaultOptions: ["إفطار صائم", "سحور", "وجبة"] },
      { key: "guestInvites", label: "دعوات الضيوف", type: "number" },
    ],
  },
  {
    id: "installments",
    title: "التقسيطات",
    subtitle: "متابعة أقساط جميع الفعاليات",
    icon: "💳",
    eventType: "__installments__",
    benefitType: "دعم فعالية",
    installmentsOnly: true,
    extraFields: [],
  },
  {
    id: "cultural",
    title: "الأنشطة الثقافية والرياضية والاجتماعية",
    subtitle: "أنشطة دورية وحضور تراكمي",
    icon: "🎭",
    eventType: "نشاط رياضي",
    benefitType: "دعم فعالية",
    extraFields: [
      { key: "activityKind", label: "نوع النشاط", listKey: "union_activity_kinds", type: "dropdown", defaultOptions: ["ثقافي", "رياضي", "اجتماعي", "ديني"] },
      { key: "recurrence", label: "التكرار", listKey: "union_recurrence", type: "dropdown", defaultOptions: ["أسبوعي", "شهري", "مرة واحدة"] },
      { key: "venue", label: "المكان", type: "text" },
      { key: "supervisor", label: "المشرف", type: "text" },
    ],
  },
  {
    id: "competitions",
    title: "المسابقات",
    subtitle: "مسابقات وجوائز للفائزين",
    icon: "🏆",
    eventType: "مسابقة ثقافية",
    benefitType: "جائزة مسابقة",
    extraFields: [
      { key: "competitionKind", label: "نوع المسابقة", listKey: "union_competition_kinds", type: "dropdown", defaultOptions: ["ثقافية", "رياضية", "دينية", "فنية"] },
      { key: "judgeCommittee", label: "لجنة التحكيم", type: "text" },
      { key: "prizes", label: "الجوائز (الأول/الثاني/الثالث)", type: "text" },
      { key: "conditions", label: "الشروط", type: "text" },
    ],
  },
  {
    id: "reservations",
    title: "الحجوزات",
    subtitle: "حجز القاعات والخدمات",
    icon: "📅",
    eventType: "حجز قاعة",
    benefitType: "دعم فعالية",
    extraFields: [
      { key: "resourceName", label: "المورد المحجوز", listKey: "union_resources", type: "dropdown", defaultOptions: ["قاعة أفراح", "قاعة اجتماعات", "أتوبيس", "شقة مصيف"] },
      { key: "reservationDate", label: "تاريخ الحجز", type: "date" },
      { key: "downPayment", label: "العربون", type: "number" },
      { key: "cancelPolicy", label: "سياسة الإلغاء", listKey: "union_cancel_policies", type: "dropdown", defaultOptions: ["استرداد كامل", "خصم العربون", "بدون استرداد"] },
    ],
  },
  {
    id: "tickets",
    title: "التذاكر",
    subtitle: "تذاكر مرقمة قابلة للتحقق",
    icon: "🎫",
    eventType: "تذاكر",
    benefitType: "خصم تذاكر",
    extraFields: [
      { key: "ticketKind", label: "نوع التذكرة", listKey: "union_ticket_kinds", type: "dropdown", defaultOptions: ["مصيف", "عرض", "نقل", "حفل"] },
      { key: "serialPrefix", label: "بادئة المسلسل", type: "text" },
      { key: "serialFrom", label: "مسلسل من", type: "number" },
      { key: "serialTo", label: "مسلسل إلى", type: "number" },
    ],
  },
  {
    id: "inkind",
    title: "الدعم العيني",
    subtitle: "صرف عيني بسندات استلام",
    icon: "📦",
    eventType: "دعم عيني",
    benefitType: "خدمة عينية",
    extraFields: [
      { key: "itemName", label: "الصنف", listKey: "union_inkind_items", type: "dropdown", defaultOptions: ["شنطة رمضان", "بطانية", "مواد غذائية", "ملابس"] },
      { key: "unit", label: "الوحدة", listKey: "union_inkind_units", type: "dropdown", defaultOptions: ["كرتونة", "قطعة", "شنطة"] },
      { key: "stockQty", label: "الكمية المتاحة", type: "number" },
      { key: "maxPerMember", label: "الحد الأقصى للعضو", type: "number" },
    ],
  },
];

export const getUnionActivityConfig = (id = "") => UNION_ACTIVITY_TYPES.find((t) => t.id === id) || null;
